### PR TITLE
39 beta wallpaper

### PR DESCRIPTION
**Pull request by jimmac**
holographic soap bubbles theme loosely based on Florence Nightingale.

### CODE REVIEW

**Comment by allanday** [comment]
Thanks for this, @jimmac !

@luyatshimbalanga is there any chance that this could be quickly merged and the F39 packages built? It's a potential F39 beta blocker (see https://bugzilla.redhat.com/show_bug.cgi?id=2230720). Sorry about it being so last minute.

**Comment by AdamWill** [comment]
thanks mo! mo has also given me commit access to the repo, so I will try and see if anything else is needed and cut a release and do the downstream package build in a few hours.

**Comment by AdamWill** [comment]
Why is this square?

The old wallpaper was 4032x3024 , which is a 4:3 aspect ratio (already a bit odd - shouldn't we go with 16x9 or 16x10 as the most common display ratios these days?). This is 4096x4096. Nobody has a square monitor. It is always going to be squished or letterboxed or unpredictably cropped, which seems suboptimal.

**Comment by ghost** [comment]
Square to suit all display types, horizontal and vertical. :)

**Comment by jimmac** [comment]
> Why is this square?

It is the perfect aspect to cover both landscape and portrait displays. While it's working great for upstream GNOME as the only wallpaper we ship, it's also good as a source for cropping to the gajillion resolutions in Fedora.

**Comment by allanday** [comment]
> It is always going to be squished or letterboxed or unpredictably cropped,

We "crop" the wallpaper by default, and we can anticipate what the most common croppings will be (see https://developer.gnome.org/hig/reference/backgrounds.html).

**Comment by AdamWill** [comment]
I meant unpredictably across different desktops. But fair point about the portrait orientation, given the variety of ways people use monitors these days I guess square's as good a choice as any.

**Pull request merged**
