### PR TITLE
Fedora 34 Wallpapers

### PR DESCRIPTION
**Pull request by mairin**
Hi Luya!

Here are the F34 wallpapers. I cropped for the various sizes, but I don't remember if we are still doing that or not. Happy to modify the PR if you dont need the extras. LMK!

If we can get it in before branching on Feb 9 that would be ideal!

### CODE REVIEW

**Review by luyatshimbalanga — CHANGES_REQUESTED** [review]
Hello @mairin 
Cropping to various size is no longer needed since Fedora 33, simply put the highest resolution images (4K version) found in Standard folder. Feel free to push a 5K version.
I switched the branch to [f34-bakgrounds](https://github.com/fedoradesign/backgrounds/tree/f34-backgrounds) where you can commit the changes. Once done, I will merge them.

**Comment by mairin** [comment]
Hey Luya I think this should do it? Does it look ok to merge?

**Review by luyatshimbalanga — CHANGES_REQUESTED** [review]
Hey Máirín,

Almost. _f34.xml_ has a mistake on the path. For example,
` <file>/usr/share/backgrounds/f33/default/f34-01-day.png</file>`
should be ` <file>/usr/share/backgrounds/f34/default/f34-01-day.png</file>`

Standard folder is unnecessary and can be removed. Simply put the images inside the _default_ folder like the above example.

**Comment by mairin** [comment]
OK cool all set now?

**Comment by luyatshimbalanga** [comment]
All set

**Pull request merged**
