### PR TITLE
Rename f36-time.xml back to f36.xml

### PR DESCRIPTION
**Pull request by AdamWill**
It is not safe to just rename this file. The schema override in
desktop-backgrounds-gnome points to exactly
/usr/share/backgrounds/fNN/default/fNN.xml (where NN is the
release number); if that file does not exist, then new user
accounts will have a broken config. Also I think when the user
account is created this string is written into their config -
so even if we changed the override to point to this new name,
anyone who installed F36 already would still have a config that
looks for f36.xml and if there is no f36.xml their background
would break.

I'm not clear whether we want the animated background or the
static night one to be the default, but whichever it is should
be installed as f36.xml, not any other name. This assumes the
one we want to be default is the animated one.

Signed-off-by: Adam Williamson <awilliam@redhat.com>

### CODE REVIEW

**Comment by AdamWill** [comment]
Since it broke GNOME backgrounds in F36 and Rawhide, I backported this patch and did 36.0.1-2 builds for both. If we want to have a static image as the default or something, we can tweak it and do another package build.

**Comment by luyatshimbalanga** [comment]
I was contacted by Allan from upstream GNOME Design Team to implement the Dark Mode support and. I will suggest to duplication f36.xml as f36-time.xml for the time being. See the reasoning on https://pagure.io/design/issue/809

**Comment by AdamWill** [comment]
Well, ultimately, the issue here is that in Fedora, the "default" background for GNOME is `/usr/share/backgrounds/fNN/default/fNN.xml`, where NN is the Fedora release number. The files `/usr/share/glib-2.0/schemas/10_org.gnome.desktop.background.fedora.gschema.override` and `/usr/share/glib-2.0/schemas/10_org.gnome.desktop.screensaver.fedora.gschema.override` from `desktop-backgrounds-gnome` are what implement that.

We can change those overrides to point elsewhere of course, but that leaves anyone who installed F36 already with broken backgrounds, I think, because the overridden value gets saved into the user's config at the time the user first logs into GNOME; if the override file is changed *after* a user is created, their configuration is not updated, AIUI. So it's kind of a problem to just suddenly remove that file.

If what we want is for the 'dark mode' background to be the default, it seems like it'd be safest/best if we can make `/usr/share/backgrounds/fNN/default/fNN.xml` be that. I don't know how to do that, though, with this setup of two slightly different types of XML file in different places doing different things.

**Comment by luyatshimbalanga** [comment]
That change is done in [desktop-backgrounds](https://src.fedoraproject.org/rpms/desktop-backgrounds/blob/rawhide/f/desktop-backgrounds.spec) at the following lines:
```
#   for GNOME
--
  | mkdir -p %{buildroot}%{_datadir}/glib-2.0/schemas
  | /bin/echo '[org.gnome.desktop.background]' > \
  | %{buildroot}%{_datadir}/glib-2.0/schemas/10_org.gnome.desktop.background.fedora.gschema.override
  | /bin/echo "picture-uri='file://%{_datadir}/backgrounds/%{fedora_release_name}/%{gnome_default}/%{fedora_release_name}.xml'" >> \
  | %{buildroot}%{_datadir}/glib-2.0/schemas/10_org.gnome.desktop.background.fedora.gschema.override
  | # Use the Fedora background on the GNOME lockscreen as well. Would be awesome to
  | # have a separate image here to complement the default Fedora background, rather
  | # than using the same image in both places, but previously we've mixed Fedora
  | # desktop backgrounds with GNOME lockscreens, and they just do not match at all.
  | /bin/echo '[org.gnome.desktop.screensaver]' > \
  | %{buildroot}%{_datadir}/glib-2.0/schemas/10_org.gnome.desktop.screensaver.fedora.gschema.override
  | /bin/echo "picture-uri='file://%{_datadir}/backgrounds/%{fedora_release_name}/%{gnome_default}/%{fedora_release_name}.xml'" >> \
 
```

**Comment by AdamWill** [comment]
Yes, but what I was struggling with is, *what* do we replace it with? But I think I see the answer: we'd change it to set `picture-uri` to `/usr/share/backgrounds/fNN/default/fNN-01-day.png` and `picture-uri-dark` to `/usr/share/backgrounds/fNN/default/fNN-02-night.png`. As long as we used those filenames consistently across releases I think that would work. I'll test it tomorrow if you don't do it sooner.

**Comment by AdamWill** [comment]
BTW, I think this rename is still a good idea because of the fact that people who already installed F36 will likely have `f36.xml` in their configs and that won't get changed.

**Comment by luyatshimbalanga** [comment]
> Yes, but what I was struggling with is, _what_ do we replace it with? But I think I see the answer: we'd change it to set `picture-uri` to `/usr/share/backgrounds/fNN/default/fNN-01-day.png` and `picture-uri-dark` to `/usr/share/backgrounds/fNN/default/fNN-02-night.png`. As long as we used those filenames consistently across releases I think that would work. I'll test it tomorrow if you don't do it sooner.

The changes applied for xml file from `picture-uri=0'file://%{_datadir}/backgrounds/%{fedora_release_name}/%{gnome_default}/%{fedora_release_name}.xml'` in this case i.e. the renamed f36.xml which includes time of the day. After several check, it looks like the commit is good enough without impacting the support of dark mode.

**Comment by AdamWill** [comment]
If we merge this and don't change desktop-backgrounds, the situation will be that both 'dark mode' and 'animated' options will be present, and the 'animated' option will be default. If we want the 'dark mode' option to be default, I think, we should merge this to keep things working for people who already installed, but *also* change `desktop-backgrounds` as I suggested above.

**Comment by luyatshimbalanga** [comment]
Let's proceed to the option #2 i.e. default dark mode to stay in sync upstream GNOME. You can start updating `desktop-backgrounds` while we update the tarball.

**Comment by AdamWill** [comment]
OK, I sent out an update for desktop-backgrounds today. Seems to work OK in my testing.

**Pull request merged**
